/** @type {HTMLCanvasElement} */

/*document.addEventListener('keydown', (e) => {

    switch(e.code) {

        case 'ArrowLeft':
            player.x -= newGame.playerSpeed;
            break

        case 'ArrowRight':
            player.x += newGame.playerSpeed;
            break

        case 'ArrowUp':
            player.y -= newGame.playerSpeed;
            break

        case 'ArrowDown':
            player.y += newGame.playerSpeed;
            break

        /* default :
            player.x = player.x ;
            player.y = player.y ; */

        
        
   /*  }
}) */



let keysPressed = {};             //Object that will store the events generated bye the keydown
let lastKey = [];



//Event Listener used to detect the keys pressed
//Used with conditional and objects to detect to keys pressed at the same time
//Enabling the player to move on a diagonal

/* document.addEventListener('keydown', (e) => {
    keysPressed[e.key] = true;
    

    if ((keysPressed['ArrowUp'] && e.key == 'ArrowLeft') || (keysPressed['ArrowLeft'] && e.key == 'ArrowUp')) {
        player.x -= newGame.playerSpeed;
        player.y -= newGame.playerSpeed;
        lastKey.key = 'ArrowUpLeft';
    }else if ((keysPressed['ArrowUp'] && e.key == 'ArrowRight') || (keysPressed['ArrowRight'] && e.key == 'ArrowUp')) {
        player.x += newGame.playerSpeed;
        player.y -= newGame.playerSpeed;
        lastKey.key = 'ArrowUpRight';
    }else if ((keysPressed['ArrowDown'] && e.key == 'ArrowLeft') || (keysPressed['ArrowLeft'] && e.key == 'ArrowDown')){
        player.x -= newGame.playerSpeed;
        player.y += newGame.playerSpeed;
        lastKey.key = 'ArrowDownLeft';
    }else if ((keysPressed['ArrowDown'] && e.key == 'ArrowRight') || (keysPressed['ArrowRight'] && e.key == 'ArrowDown')){
        player.x += newGame.playerSpeed;
        player.y += newGame.playerSpeed;
        lastKey.key = 'ArrowDownRight';
    }else if (e.key == 'ArrowUp'){
        player.y -= newGame.playerSpeed;
        lastKey.key = 'ArrowUp';
    }else if(e.key == 'ArrowDown'){
        player.y += newGame.playerSpeed;
        lastKey.key = 'ArrowDown';
    }else if(e.key == 'ArrowLeft'){
        player.x -= newGame.playerSpeed;
        lastKey.key = 'ArrowLeft';
    }else if(e.key == 'ArrowRight'){
        player.x += newGame.playerSpeed;
        lastKey.key = 'ArrowRight';
    }
 */
    //let keysArray = lastKey.splice(-1, 2);
    document.addEventListener('keydown', (e) => {
        
        
        switch(e.code) {

            case 'ArrowUp':
                player.speedY =- 4;
                lastKey.push('ArrowUp');
                console.log(lastKey)
                break;

            case 'ArrowDown':
                player.speedY = 4;
                lastKey.push('ArrowDown');
                break;   
                
            case 'ArrowLeft':
                player.speedX = -4;
                lastKey.push('ArrowLeft');
                break;  

            case 'ArrowRight':
                player.speedX = 4;
                lastKey.push('ArrowRight');
                break;  

            case 'Space':
                shot.x = player.x;
                shot.y = player.y;
                let direction = lastKey.splice(-2,2);
                
                

                if(direction.includes('ArrowUp') && direction.includes('ArrowLeft')) {
                    shot.firstShot('ArrowUpLeft')
                    console.log(direction);
                    lastKey = [];
                }else if(direction.includes('ArrowUp') && direction.includes('ArrowRight')){
                    shot.firstShot('ArrowUpRight');
                    lastKey = [];
                } else if(direction.includes('ArrowDown') && direction.includes('ArrowLeft')){
                    shot.firstShot('ArrowDownLeft');
                    lastKey = []
                } else if(direction.includes('ArrowDown') && direction.includes('ArrowRight')){
                    shot.firstShot('ArrowDownRight');
                    lastKey = []
                } else if(direction.length < 2 && direction.includes('ArrowUp')){
                    shot.firstShot('ArrowUp');
                    lastKey = []

                } else if(lastKey.length < 2 && lastKey.includes('ArrowDown')){
                    shot.firstShot('ArrowDown');
                    lastKey = [];
                } else if(lastKey.length < 2 && lastKey.includes('ArrowLeft')){
                    shot.firstShot('ArrowLeft');
                    lastKey = [];
                } else if(lastKey.length < 2 && lastKey.includes('ArrowRight')){
                    shot.firstShot('ArrowRight');
                    lastKey = [];
                } 
                
                
                
                
                
                
                
                console.log(lastKey);
                break;
        }
            
    });
    /* if(keysPressed[' ']){               //tecla espaço
       shot.x = player.x;
       shot.y = player.y;
       shot.firstShot(lastKey.key);
    } */





document.addEventListener('keyup', (e) => {

    /* delete keysPressed[e.key]; */
    switch(e.code) {
    case 'ArrowUp':
        player.speedY = 0;
        //lastKey = [];
        break;

    case 'ArrowDown':
        player.speedY = 0;
        //lastKey = [];
        break;   
        
    case 'ArrowLeft':
        player.speedX = 0;
        //lastKey = [];
        break;  

    case 'ArrowRight':
        player.speedX = 0;
        //lastKey = [];
        break; 

    }

}) 